[project]
name = "pcs2ics"
version = "0.1.0"
description = "Export PCS (procyclingstats.com) calendar search as an ics file"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "ics>=0.7.2",
    "lxml>=6.0.2",
    "requests>=2.32.5",
]
